/**
 * PG_RFP_SPEC.md §6 시나리오 A — 구매사 RFP 발송.
 *
 * Buyer logs in, creates a new RFP, supplies allowed PG emails (3),
 * submits, lands on the RFP detail page. Verifies:
 *   - rfps row inserted with status='sent'
 *   - rfp_invitations × 3 (one per PG email)
 *   - outbox_entries × 4 (1 rfp.sent + 3 rfp.invited)
 *   - UI: comparison table shows 0 bids
 *
 * State: globalSetup truncated + reseeded the test DB. Buyer
 * `yeonseong.dev@gmail.com` has bizProfile with bizNo `123-45-67890`
 * and grade `sme2`. We do NOT touch the seeded `P-2604-0001` RFP —
 * scenario A creates a fresh one whose ID is auto-generated by
 * `nextRfpId()` (YYMM + seq).
 */
import { test, expect } from 'playwright/test';
import { sql } from 'drizzle-orm';
import { db } from '@/lib/db/client';
import { rfpUuidFromCode } from './_helpers';

// Force the DB client to point at the test DB before importing it.
// playwright globalSetup already set this in the parent process; this
// ensures any worker that re-imports the module also uses the test URL.
process.env.DATABASE_URL =
  process.env.DATABASE_URL_TEST ??
  'postgres://supporter_b:supporter_b@localhost:5433/supporter_b_test';

const BUYER_EMAIL = 'yeonseong.dev@gmail.com';
const BUYER_PASSWORD = 'password123';

test.describe.serial('Scenario A — buyer creates and sends RFP', () => {
  test('buyer logs in, creates RFP, sends to 3 PGs, lands on detail page', async ({
    page,
  }) => {
    // ── 1. Login ─────────────────────────────────────────────────
    await page.goto('/login');
    await page.fill('input[name="email"]', BUYER_EMAIL);
    await page.fill('input[name="password"]', BUYER_PASSWORD);
    await page.getByRole('button', { name: '로그인' }).click();
    await expect(page).toHaveURL(/\/home$/, { timeout: 15_000 });

    // ── 2. Open the new-RFP wizard (step 1 사업자 확인) ──────────
    // /rfp/new 는 4-step 위저드(1 사업자 확인 · 2 제안 내용 · 3 PG 선택 ·
    // 4 발송 확인). 각 단계는 'use client' RfpCreateWizard 가 렌더하며 '다음'
    // 버튼으로 진행한다.
    await page.goto('/rfp/new');
    await expect(
      page.getByRole('heading', { name: '신규 제안 요청' }),
    ).toBeVisible();
    // Step 1 renders the workspace bizProfile (123-45-67890) — verify the
    // page didn't redirect to a "missing workspace bizProfile" branch, then
    // advance to step 2.
    await expect(page.getByText('123-45-67890')).toBeVisible();
    await page.getByRole('button', { name: '다음' }).click();

    // ── 3. Step 2 제안 내용 — 필수: 제목 + 견적 받을 결제수단 ────
    // 나머지 사업 컨텍스트 input(홈페이지/주판/거래액/…)은 optional.
    // createRfpAction 은 send 시 requiredPaymentMethods+custom ≥1 을 강제하므로
    // (zod superRefine → 미선택 시 INVALID_INPUT, 발송 차단) 결제수단도 선택.
    await page
      .getByPlaceholder('2026 서포트쇼핑몰 결제 인프라 제안건')
      .fill('e2e-A-2026 결제 인프라 제안');
    await page
      .getByPlaceholder(/카드결제·간편결제 통합 솔루션 검토 중입니다/)
      .fill('e2e scenario A — automated send');
    // 견적 받을 결제수단 * — RfpPaymentMethodSelect 의 토글 버튼. '카드' 는
    // '해외카드' 와 부분일치하므로 exact 로 좁힌다.
    await page.getByRole('button', { name: '카드', exact: true }).click();
    await page.getByRole('button', { name: '다음' }).click();

    // ── 3b. Step 3 PG 선택 — Popover + cmdk Command ────────────
    // click "PG사 검색…" trigger → list loads via /api/workspaces/search
    // → click each workspace (role=option) → Popover closes → re-open.
    // Seed workspaces: '서포터 B 페이', 'KG이니시스', '카카오페이'.
    const pgNames = ['서포터 B 페이', 'KG이니시스', '카카오페이'];
    for (const name of pgNames) {
      await page.getByRole('button', { name: 'PG사 검색…' }).click();
      await page.getByRole('option', { name }).click();
    }
    await page.getByRole('button', { name: '다음' }).click();

    // ── 4. Step 4 발송 확인 — 마감일(필수) + 발송 ──────────────
    // Pick a future deadline (input[type=date] — required to enable send).
    const tomorrow = new Date(Date.now() + 7 * 86_400_000)
      .toISOString()
      .slice(0, 10);
    await page.locator('input[type="date"]').fill(tomorrow);
    // Send button text reflects count: "3개 PG사에 발송". Anchor the full name so
    // it doesn't also match the sidebar step button "발송 확인" (strict-mode).
    await page.getByRole('button', { name: /^\d+개 PG사에 발송$/ }).click();

    // ── 5. Land on /rfp/<rfpId> ──────────────────────────────────
    await page.waitForURL(/\/rfp\/P-\d{4}-\d{4}$/, { timeout: 15_000 });
    const url = new URL(page.url());
    const rfpId = url.pathname.split('/').pop()!;
    expect(rfpId).toMatch(/^P-\d{4}-\d{4}$/);
    // URL/seed identifier is the human code; FK columns + dedupe keys use the uuid.
    const rfpUuid = await rfpUuidFromCode(rfpId);

    // Comparison table shows zero bids since no PG has submitted.
    // BidComparisonTable renders an EmptyState with this exact copy when
    // bids.length === 0 (see components/rfp/BidComparisonTable.tsx).
    await expect(
      page.getByText('제안을 기다리는 중이에요.'),
    ).toBeVisible({ timeout: 10_000 });

    // ── 6. DB assertions ─────────────────────────────────────────
    const rfpRows = await db.execute<{ id: string; status: string }>(
      sql`SELECT id, status FROM rfps WHERE id = ${rfpUuid}`,
    );
    const rfpArr = Array.isArray(rfpRows)
      ? rfpRows
      : // eslint-disable-next-line @typescript-eslint/no-explicit-any
        ((rfpRows as any).rows ?? []);
    expect(rfpArr).toHaveLength(1);
    expect(rfpArr[0].status).toBe('sent');

    const inviteRows = await db.execute<{ c: number }>(
      sql`SELECT count(*)::int AS c FROM rfp_invitations WHERE rfp_id = ${rfpUuid}`,
    );
    const inviteArr = Array.isArray(inviteRows)
      ? inviteRows
      : // eslint-disable-next-line @typescript-eslint/no-explicit-any
        ((inviteRows as any).rows ?? []);
    expect(inviteArr[0].c).toBe(3);

    // Outbox: 3 rfp.invited entries (one per PG admin), scoped to this RFP.
    // createRfpAction enqueues ONLY rfp.invited rows; `rfp.sent` is a
    // logBusinessEvent(), not an outbox email — see createRfpAction.ts and the
    // canonical unit contract create.test.ts:184-186 (every row rfp.invited,
    // no rfp.sent). dedupeKey: `rfp:{rfpId}:invite:ws:{pgWsId}:user:{u}`.
    const outboxRows = await db.execute<{ c: number }>(
      sql`SELECT count(*)::int AS c FROM outbox_entries
          WHERE event IN ('rfp.sent', 'rfp.invited')
            AND dedupe_key LIKE ${'rfp:' + rfpUuid + ':%'}`,
    );
    const outboxArr = Array.isArray(outboxRows)
      ? outboxRows
      : // eslint-disable-next-line @typescript-eslint/no-explicit-any
        ((outboxRows as any).rows ?? []);
    expect(outboxArr[0].c).toBe(3);
  });
});
