/**
 * PG_RFP_SPEC.md §6 시나리오 A — 구매사 RFP 발송.
 *
 * Buyer logs in, creates a new RFP, supplies allowed PG emails (3),
 * submits, lands on the RFP detail page. Verifies:
 *   - rfps row inserted with status='sent'
 *   - rfp_invitations × 3 (one per PG email)
 *   - outbox_entries — rfp.invited 만, **PG 워크스페이스당이 아니라 승인 멤버당 1건**
 *     (rfp.sent 은 아웃박스 행이 아니라 logBusinessEvent 다, createRfpAction:179-184)
 *   - UI: comparison table shows 0 bids
 *
 * State: globalSetup truncated + reseeded the test DB. Buyer
 * `yeonseong.dev@gmail.com` has bizProfile with bizNo `123-45-67890`
 * and grade `sme2`. We do NOT touch the seeded `P-2604-0001` RFP —
 * scenario A creates a fresh one whose ID is auto-generated by
 * `nextRfpId()` (YYMM + seq).
 */
import { test, expect } from 'playwright/test';
import { sql } from 'drizzle-orm';
import { db } from '@/lib/db/client';
import { rfpUuidFromCode } from './_helpers';

// Force the DB client to point at the test DB before importing it.
// playwright globalSetup already set this in the parent process; this
// ensures any worker that re-imports the module also uses the test URL.
process.env.DATABASE_URL =
  process.env.DATABASE_URL_TEST ??
  'postgres://supporter_b:supporter_b@localhost:5433/supporter_b_test';

const BUYER_EMAIL = 'yeonseong.dev@gmail.com';
const BUYER_PASSWORD = 'password123';

test.describe.serial('Scenario A — buyer creates and sends RFP', () => {
  test('buyer logs in, creates RFP, sends to 3 PGs, lands on detail page', async ({
    page,
  }) => {
    // ── 1. Login ─────────────────────────────────────────────────
    await page.goto('/login');
    await page.fill('input[name="email"]', BUYER_EMAIL);
    await page.fill('input[name="password"]', BUYER_PASSWORD);
    await page.getByRole('button', { name: '로그인' }).click();
    await expect(page).toHaveURL(/\/home$/, { timeout: 15_000 });

    // ── 2. Open the new-RFP wizard (step 1 사업자 확인) ──────────
    // /rfp-create 는 4-step 위저드(1 사업자 확인 · 2 제안 내용 · 3 PG 선택 ·
    // 4 발송 확인). 각 단계는 'use client' RfpCreateWizard 가 렌더하며 '다음'
    // 버튼으로 진행한다.
    await page.goto('/rfp-create');
    await expect(
      page.getByRole('heading', { name: '새 견적 요청' }),
    ).toBeVisible();
    // Step 1 renders the workspace bizProfile (123-45-67890) — verify the
    // page didn't redirect to a "missing workspace bizProfile" branch, then
    // advance to step 2.
    await expect(page.getByText('123-45-67890')).toBeVisible();
    await page.getByRole('button', { name: '다음' }).click();

    // ── 3. Step 2 제안 내용 — 필수: 제목 + 홈페이지 + 견적 유형 +
    // 주요 판매 상품 + 연간 PG 총 거래액 + 견적 받을 결제수단 ────
    // 위저드 'use client' 검증(wizard-validation)이 이 6개를 모두 채워야 '다음'을
    // 허용하고, createRfpAction 은 send 시 동일 필드를 zod superRefine 으로 재강제한다.
    await page
      .getByPlaceholder('2026 서포트쇼핑몰 결제 인프라 견적 요청')
      .fill('e2e-A-2026 결제 인프라 제안');
    await page.getByPlaceholder('example.com').fill('example.com');
    const newContract = page.getByRole('button', { name: '신규 계약' });
    await newContract.click();
    // 견적 유형 버튼은 토글이다 — 이중 클릭으로 null 로 돌아가지 않았음을 못박는다.
    await expect(newContract).toHaveAttribute('aria-pressed', 'true');
    await page.getByPlaceholder('의류').fill('의류');
    // 신규 계약(첫 PG 계약)은 PG 계약 이력이 존재할 수 없어 그 블록을 통째로 숨긴다
    // (RfpStep2Content:66,153-223). 전년도 거래액도 필수에서 빠진다
    // (required-fields.ts:isAnnualPgVolumeSatisfied) — 서버도 같은 판정으로 strip 한다
    // (createRfpAction:106,166). 숨김을 단언으로 고정해 두면 누가 되살릴 때 여기서 깨진다.
    await expect(page.getByPlaceholder('10억')).toHaveCount(0);
    // 견적 요청 세부 내용(memo)은 optional. placeholder 가 자주 바뀌므로 step 2
    // 의 유일한 <textarea> 를 직접 노린다.
    await page
      .locator('textarea')
      .fill('e2e scenario A — automated send');
    // 견적 받을 결제수단 * — RfpPaymentMethodSelect 의 토글 버튼. '카드' 는
    // '해외카드' 와 부분일치하므로 exact 로 좁힌다.
    await page.getByRole('button', { name: '카드', exact: true }).click();
    await page.getByRole('button', { name: '다음' }).click();

    // ── 3b. Step 3 PG 선택 — 칩 토글 리스트 (RfpStep3PgSelect) ──
    // 위저드는 첫 마운트에서 사용 가능한 PG 를 **전부 자동 선택**한다
    // (RfpCreateWizard:74-80, 신선한 컨텍스트는 항상 이 경로). 칩을 다시 누르면
    // '해제'라, 예전처럼 시드 PG 3곳을 순회 클릭하면 셋 다 꺼져 이 단계에서 막힌다.
    // 선택 상태의 관측점은 두 개다 — 칩의 aria-pressed 와 헤더 카운터.
    // (칩 토글 자체는 RfpStep3PgSelect.test.tsx 가 유닛으로 덮는다.)
    // Seed workspaces: '서포터 B 페이', 'KG이니시스', '카카오페이'.
    await expect(page.getByTestId('pg-select-count')).toContainText('3/3');
    await expect(page.getByRole('button', { pressed: true })).toHaveCount(3);
    await page.getByRole('button', { name: '다음' }).click();

    // ── 4. Step 4 발송 확인 — 마감일(필수) + 발송 ──────────────
    // Pick a future deadline (input[type=date] — required to enable send).
    const tomorrow = new Date(Date.now() + 7 * 86_400_000)
      .toISOString()
      .slice(0, 10);
    await page.locator('input[type="date"]').fill(tomorrow);
    // Send button text reflects count: "3개 PG사에 보내기". Anchor the full name so
    // it doesn't also match the sidebar step button "최종 견적 요청 정보 확인" (strict-mode).
    // 개수까지 고정한다 — 선택이 어긋나면 40줄 뒤 DB 단언이 아니라 여기서 죽는다.
    await page.getByRole('button', { name: /^3개 PG사에 보내기$/ }).click();

    // ── 5. Land on /rfp/<rfpId> ──────────────────────────────────
    await page.waitForURL(/\/rfp\/P-\d{4}-\d{4}$/, { timeout: 15_000 });
    const url = new URL(page.url());
    const rfpId = url.pathname.split('/').pop()!;
    expect(rfpId).toMatch(/^P-\d{4}-\d{4}$/);
    // URL/seed identifier is the human code; FK columns + dedupe keys use the uuid.
    const rfpUuid = await rfpUuidFromCode(rfpId);

    // 비교 영역(FocusComparison)은 제출된 견적이 0건이면 EmptyState 를 그린다
    // (see components/rfp/comparison/FocusComparison.tsx).
    await expect(
      page.getByText('견적을 기다리고 있어요'),
    ).toBeVisible({ timeout: 10_000 });

    // ── 6. DB assertions ─────────────────────────────────────────
    const rfpRows = await db.execute<{ id: string; status: string }>(
      sql`SELECT id, status FROM rfps WHERE id = ${rfpUuid}`,
    );
    const rfpArr = Array.isArray(rfpRows)
      ? rfpRows
      : // eslint-disable-next-line @typescript-eslint/no-explicit-any
        ((rfpRows as any).rows ?? []);
    expect(rfpArr).toHaveLength(1);
    expect(rfpArr[0].status).toBe('sent');

    const inviteRows = await db.execute<{ c: number }>(
      sql`SELECT count(*)::int AS c FROM rfp_invitations WHERE rfp_id = ${rfpUuid}`,
    );
    const inviteArr = Array.isArray(inviteRows)
      ? inviteRows
      : // eslint-disable-next-line @typescript-eslint/no-explicit-any
        ((inviteRows as any).rows ?? []);
    expect(inviteArr[0].c).toBe(3);

    // Outbox: rfp.invited 는 **PG 워크스페이스당 1건이 아니라 승인 멤버당 1건**이다
    // (rfp.ts:1007-1040 이 approvedMemberRecipients 로 팬아웃하고 dedupeKey 가
    // `…:ws:{pgWsId}:user:{userId}` 로 끝난다). 시드의 '서포터 B 페이' 는 멤버가 둘이라
    // 3개 PG 에 보내도 4건이 된다 — 그래서 기대값을 상수로 박지 않고 **같은 규칙에서
    // 파생**시킨다. 상수 3 을 박아 두면 시드 멤버십이 바뀔 때마다 스펙이 거짓말을 한다.
    // createRfpAction 은 rfp.invited 만 enqueue 한다 — `rfp.sent` 는 outbox 가 아니라
    // logBusinessEvent 다(createRfpAction:179-184, 유닛 계약은 create.test.ts:184-186).
    const expectedRows = await db.execute<{ c: number }>(
      sql`SELECT count(*)::int AS c
          FROM rfp_allowed_pg a
          JOIN workspace_members m ON m.workspace_id = a.pg_ws_id
          WHERE a.rfp_id = ${rfpUuid} AND m.approval_status = 'approved'`,
    );
    const expectedArr = Array.isArray(expectedRows)
      ? expectedRows
      : // eslint-disable-next-line @typescript-eslint/no-explicit-any
        ((expectedRows as any).rows ?? []);
    expect(expectedArr[0].c).toBeGreaterThanOrEqual(3);

    const outboxRows = await db.execute<{ c: number; ws: number }>(
      sql`SELECT count(*)::int AS c, count(DISTINCT split_part(dedupe_key, ':', 5))::int AS ws
          FROM outbox_entries
          WHERE event IN ('rfp.sent', 'rfp.invited')
            AND dedupe_key LIKE ${'rfp:' + rfpUuid + ':%'}`,
    );
    const outboxArr = Array.isArray(outboxRows)
      ? outboxRows
      : // eslint-disable-next-line @typescript-eslint/no-explicit-any
        ((outboxRows as any).rows ?? []);
    expect(outboxArr[0].c).toBe(expectedArr[0].c);
    // 그리고 세 PG 워크스페이스가 **모두** 실제로 커버됐다(한 곳에 4통이 아니다).
    expect(outboxArr[0].ws).toBe(3);
  });
});
