/**
 * LocalStorage — disk-backed `Storage` implementation for v0 single-node
 * deployments. `STORAGE_ROOT` defaults to `./uploads` relative to repo
 * root (overridable via `UPLOAD_DIR`). Files live at
 * `${STORAGE_ROOT}/${key}` where `key` is `{yyyy}/{mm}/{uuid}.{ext}`
 * generated by `path.ts:newAttachmentPath`.
 *
 * v0 assumption: single instance. **prod multi-instance must swap to**
 * **S3 / Supabase Storage** — implement another class against `Storage`
 * and route `getStorage()` to it. Don't reach into `fs` outside this
 * module.
 *
 * `read` does not return mime — the route handler uses the attachment
 * row's mime_type (magic-byte sniffed at upload). See `index.ts` header.
 */
import { promises as fsp, createReadStream } from 'node:fs';
import path from 'node:path';
import { Readable } from 'node:stream';

export interface Storage {
  /** Persist `buffer` at `key`. Mime is recorded in the attachment row,
   *  not on disk; carrying it through here is informational only and
   *  lets future S3 impls thread `Content-Type` to the put request. */
  save(key: string, buffer: Buffer, mime: string): Promise<void>;
  /** Open a streaming reader. Caller composes `Content-Type` from the
   *  attachment row's mime_type, not from disk inspection. */
  read(key: string): Promise<{ stream: ReadableStream<Uint8Array>; size: number }>;
  /** Best-effort delete; ENOENT is swallowed so cleanup paths after
   *  failed inserts don't double-fault. */
  delete(key: string): Promise<void>;
}

function resolveRoot(): string {
  const raw = process.env.UPLOAD_DIR ?? './uploads';
  // Allow absolute paths (tests use os.tmpdir(); deploys may pin a volume
  // mount). Relative paths resolve from cwd which is the repo root in
  // both `next dev` and `next start`.
  return path.isAbsolute(raw) ? raw : path.resolve(process.cwd(), raw);
}

export class LocalStorage implements Storage {
  // Resolved per-call so vitest's per-test `process.env.UPLOAD_DIR`
  // overrides take effect without rebuilding the singleton.
  private root(): string {
    return resolveRoot();
  }

  async save(key: string, buffer: Buffer, _mime: string): Promise<void> {
    const full = path.join(this.root(), key);
    await fsp.mkdir(path.dirname(full), { recursive: true });
    // Cast to Uint8Array — TS 6 narrows `Buffer.buffer` to ArrayBufferLike
    // (SharedArrayBuffer-friendly union) but `fsp.writeFile` wants the
    // strict ArrayBuffer-backed view. Buffer extends Uint8Array at runtime.
    await fsp.writeFile(full, buffer as unknown as Uint8Array);
  }

  async read(key: string): Promise<{ stream: ReadableStream<Uint8Array>; size: number }> {
    const full = path.join(this.root(), key);
    const stat = await fsp.stat(full);
    const node = createReadStream(full);
    // Next 16's Response body wants Web ReadableStream — Readable.toWeb
    // bridges Node streams without buffering the whole file.
    const stream = Readable.toWeb(node) as ReadableStream<Uint8Array>;
    return { stream, size: stat.size };
  }

  async delete(key: string): Promise<void> {
    const full = path.join(this.root(), key);
    try {
      await fsp.unlink(full);
    } catch (err) {
      // Idempotent — missing file is fine for cleanup paths.
      if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err;
    }
  }
}
